# Generated by Django 5.0 on 2023-12-29 18:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payments", "0002_alter_supplyinvoice_supplier"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="supplyinvoice",
            name="amount_owed",
        ),
        migrations.AddField(
            model_name="supplyinvoice",
            name="amount_expected",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=100),
        ),
        migrations.AddField(
            model_name="supplyinvoice",
            name="amount_paid",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=100),
        ),
        migrations.AlterField(
            model_name="supplyinvoice",
            name="status",
            field=models.CharField(
                choices=[
                    ("Paid", "Paid"),
                    ("Cancelled", "Cancelled"),
                    ("Payment Pending", "Payment Pending"),
                    ("Defaulted", "Defaulted"),
                    ("Paying", "Paying"),
                ],
                max_length=255,
            ),
        ),
    ]
