# Generated by Django 5.0 on 2023-12-29 16:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_alter_user_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("admin", "Admin"),
                    ("cashier", "Cashier"),
                    ("agent", "Agent"),
                    ("broker", "Broker"),
                    ("Supplier", "Supplier"),
                ],
                max_length=32,
                null=True,
            ),
        ),
    ]
