# Generated by Django 5.0 on 2024-01-02 15:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_customer_user_created_user_modified"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="created",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="customer",
            name="modified",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="created",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="modified",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
