# Generated by Django 5.0 on 2024-01-13 11:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0006_user_position"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="created",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="customer",
            name="modified",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="user",
            name="created",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="user",
            name="modified",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
