# Generated by Django 5.0 on 2024-01-02 15:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("suppliers", "0003_alter_supplier_created_alter_supplier_modified_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="supplier",
            name="created",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="supplier",
            name="modified",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="supplylog",
            name="created",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="supplylog",
            name="modified",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
