# Generated by Django 5.0 on 2024-01-02 15:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="platformlog",
            name="created",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="platformlog",
            name="modified",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
