sample_products = [
    {
        "name": "Maize flour",
        "buying_price": 100,
        "selling_price": 120,
        "quantity": 100,
        "unit_of_measure": "kg",
    },
    {
        "name": "Rice",
        "buying_price": 200,
        "selling_price": 240,
        "quantity": 50,
        "unit_of_measure": "kg",
    },
    {
        "name": "Sugar",
        "buying_price": 300,
        "selling_price": 360,
        "quantity": 25,
        "unit_of_measure": "kg",
    },
    {
        "name": "Milk",
        "buying_price": 400,
        "selling_price": 480,
        "quantity": 10,
        "unit_of_measure": "ltr",
    },
    {
        "name": "Soap",
        "buying_price": 500,
        "selling_price": 600,
        "quantity": 20,
        "unit_of_measure": "bar",
    },
    {
        "name": "Cooking oil",
        "buying_price": 600,
        "selling_price": 720,
        "quantity": 15,
        "unit_of_measure": "ltr",
    },
    {
        "name": "Tea leaves",
        "buying_price": 700,
        "selling_price": 840,
        "quantity": 10,
        "unit_of_measure": "pkt",
    },
    {
        "name": "Salt",
        "buying_price": 800,
        "selling_price": 960,
        "quantity": 5,
        "unit_of_measure": "kg",
    },
    {
        "name": "Biscuits",
        "buying_price": 900,
        "selling_price": 1080,
        "quantity": 15,
        "unit_of_measure": "pkt",
    },
    {
        "name": "Chocolate",
        "buying_price": 1000,
        "selling_price": 1200,
        "quantity": 10,
        "unit_of_measure": "bar",
    },
    {
        "name": "Bread",
        "buying_price": 50,
        "selling_price": 60,
        "quantity": 50,
        "unit_of_measure": "loaf",
    },
    {
        "name": "Eggs",
        "buying_price": 10,
        "selling_price": 12,
        "quantity": 100,
        "unit_of_measure": "dozen",
    },
    {
        "name": "Potatoes",
        "buying_price": 20,
        "selling_price": 24,
        "quantity": 25,
        "unit_of_measure": "kg",
    },
    {
        "name": "Onions",
        "buying_price": 30,
        "selling_price": 36,
        "quantity": 15,
        "unit_of_measure": "kg",
    },
    {
        "name": "Tomatoes",
        "buying_price": 40,
        "selling_price": 48,
        "quantity": 10,
        "unit_of_measure": "kg",
    },
    {
        "name": "Cabbages",
        "buying_price": 50,
        "selling_price": 60,
        "quantity": 5,
        "unit_of_measure": "head",
    },
]
