# Generated by Django 5.0 on 2024-01-13 11:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_alter_platformlog_created_alter_platformlog_modified"),
    ]

    operations = [
        migrations.AlterField(
            model_name="platformlog",
            name="created",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="platformlog",
            name="modified",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
