# Generated by Django 5.0 on 2023-12-29 18:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payments", "0004_supplyinvoice_date_due"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="supplyinvoice",
            name="status",
            field=models.CharField(
                choices=[
                    ("Paid", "Paid"),
                    ("Cancelled", "Cancelled"),
                    ("Payment Pending", "Payment Pending"),
                    ("Defaulted", "Defaulted"),
                    ("Paying", "Paying"),
                    ("Review", "Review"),
                ],
                max_length=255,
            ),
        ),
        migrations.CreateModel(
            name="SupplyInvoiceLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("action", models.CharField(max_length=255)),
                (
                    "actioned_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "invoice",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="payments.supplyinvoice",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
