# Generated by Django 5.0 on 2024-01-13 11:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payments", "0007_alter_supplyinvoice_created_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="supplyinvoice",
            name="created",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="supplyinvoice",
            name="modified",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="supplyinvoicelog",
            name="created",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="supplyinvoicelog",
            name="modified",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
