# Generated by Django 5.0.6 on 2024-08-12 16:48

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0008_alter_supplyinvoice_created_and_more"),
        ("pos", "0019_alter_order_order_type_alter_order_payment_method"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrderPayment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(default=django.utils.timezone.now)),
                ("modified", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "amount_expected",
                    models.DecimalField(decimal_places=2, default=0, max_digits=100),
                ),
                (
                    "payment_type",
                    models.CharField(
                        choices=[("Mpesa", "Mpesa"), ("Paystack", "Paystack")],
                        max_length=255,
                    ),
                ),
                ("checkout_id", models.CharField(max_length=255, null=True)),
                ("payment_reference", models.CharField(max_length=255, null=True)),
                ("paid", models.BooleanField(default=False)),
                (
                    "order",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="pos.order"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
