# Generated by Django 4.1.7 on 2023-11-09 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Inventory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                ("buying_price", models.DecimalField(decimal_places=2, max_digits=100)),
                (
                    "selling_price",
                    models.DecimalField(decimal_places=2, max_digits=100),
                ),
                ("quantity", models.FloatField(default=0)),
                (
                    "unit_of_measure",
                    models.CharField(
                        choices=[
                            ("Kilogram", "Kilograms"),
                            ("Litres", "Litres"),
                            ("Units", "Units"),
                            ("Cartons", "Cartons"),
                            ("Pieces", "Pieces"),
                            ("Metres", "Metres"),
                        ],
                        max_length=255,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="InventoryLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("Buy", "Buy"),
                            ("Sale", "Sale"),
                            ("Damaged", "Damaged"),
                        ],
                        max_length=255,
                    ),
                ),
                ("quantity", models.FloatField(default=0)),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inventory.inventory",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
