# Generated by Django 4.1.7 on 2023-11-09 13:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inventory",
            name="unit_of_measure",
            field=models.CharField(max_length=255),
        ),
    ]
