# Generated by Django 5.0 on 2024-01-13 11:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("suppliers", "0004_alter_supplier_created_alter_supplier_modified_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="supplier",
            name="created",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="supplier",
            name="modified",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="supplylog",
            name="created",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="supplylog",
            name="modified",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
