# Generated by Django 5.0 on 2024-01-13 11:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("inventory", "0010_alter_inventory_created_alter_inventory_modified_and_more"),
        ("pos", "0010_creditorder"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductSale",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("total_quantity", models.FloatField(default=0)),
                (
                    "total_price",
                    models.DecimalField(decimal_places=2, default=2, max_digits=100),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inventory.inventory",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="pos.order"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
