# Generated by Django 5.0 on 2024-01-13 11:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reports", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="productsale",
            name="unit_price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=100),
        ),
        migrations.AlterField(
            model_name="productsale",
            name="total_price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=100),
        ),
    ]
