# Generated by Django 5.0 on 2024-01-02 19:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0005_alter_customer_created_alter_customer_modified_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="position",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
