# Generated by Django 5.0.6 on 2024-07-30 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0008_customer_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customer",
            name="gender",
        ),
        migrations.RemoveField(
            model_name="customer",
            name="id_number",
        ),
        migrations.RemoveField(
            model_name="customer",
            name="phone_number",
        ),
    ]
