# Generated by Django 5.0.6 on 2024-07-30 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0009_remove_customer_gender_remove_customer_id_number_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customer",
            name="email",
        ),
        migrations.RemoveField(
            model_name="customer",
            name="name",
        ),
    ]
