# Generated by Django 5.0.6 on 2024-07-30 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0010_remove_customer_email_remove_customer_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="gender",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="user",
            name="phone_number",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("admin", "Admin"),
                    ("cashier", "Cashier"),
                    ("agent", "Agent"),
                    ("broker", "Broker"),
                    ("Supplier", "Supplier"),
                ],
                max_length=32,
            ),
        ),
    ]
