# Generated by Django 5.0.6 on 2024-07-31 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0011_alter_user_gender_alter_user_phone_number_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="name",
            field=models.CharField(default="Walk In Customer", max_length=255),
        ),
    ]
