# Generated by Django 5.0.6 on 2024-07-31 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0012_customer_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("admin", "Admin"),
                    ("cashier", "Cashier"),
                    ("agent", "Agent"),
                    ("broker", "Broker"),
                    ("Supplier", "Supplier"),
                    ("Customer", "Customer"),
                ],
                max_length=32,
            ),
        ),
    ]
