# Generated by Django 5.0.6 on 2024-08-09 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0013_alter_user_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("admin", "Admin"),
                    ("cashier", "Cashier"),
                    ("agent", "Agent"),
                    ("broker", "Broker"),
                    ("Supplier", "Supplier"),
                    ("Customer", "Customer"),
                    ("Driver", "Driver"),
                ],
                max_length=32,
            ),
        ),
    ]
