# Generated by Django 5.0 on 2023-12-27 19:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0003_mpesapayment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inventorylog",
            name="action",
            field=models.CharField(
                choices=[
                    ("Buy", "Buy"),
                    ("Sale", "Sale"),
                    ("Damaged", "Damaged"),
                    ("Stolen", "Stolen"),
                    ("Family", "Family use"),
                    ("Fashion", "Out of fashion"),
                    ("New Stock", "New Stock"),
                ],
                max_length=255,
            ),
        ),
    ]
