# Generated by Django 5.0 on 2023-12-29 11:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0004_alter_inventorylog_action"),
    ]

    operations = [
        migrations.AddField(
            model_name="inventory",
            name="brand",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
