# Generated by Django 5.0 on 2023-12-29 12:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0006_inventorylog_actioned_by"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inventorylog",
            name="item",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="inventory.inventory",
            ),
        ),
    ]
