# Generated by Django 5.0 on 2024-01-02 15:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0009_alter_inventory_created_alter_inventory_modified_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inventory",
            name="created",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="inventory",
            name="modified",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="inventorylog",
            name="created",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="inventorylog",
            name="modified",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="mpesapayment",
            name="created",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="mpesapayment",
            name="modified",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
