# Generated by Django 5.0 on 2024-01-13 11:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0010_alter_inventory_created_alter_inventory_modified_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inventory",
            name="created",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="inventory",
            name="modified",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="inventorylog",
            name="created",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="inventorylog",
            name="modified",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="mpesapayment",
            name="created",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="mpesapayment",
            name="modified",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
