# Generated by Django 5.0.6 on 2024-07-30 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0013_productcategory_inventory_profile_photo_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="inventory",
            old_name="profile_photo",
            new_name="image",
        ),
    ]
