# Generated by Django 5.0.6 on 2024-08-03 06:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_measureunit"),
        ("inventory", "0015_remove_inventory_unit_of_measure"),
    ]

    operations = [
        migrations.AddField(
            model_name="inventory",
            name="unit_of_measure",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.measureunit",
            ),
        ),
    ]
