# Generated by Django 5.0 on 2023-12-30 14:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pos", "0003_temporarycustomercartitem_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="temporarycustomercartitem",
            name="cashier_id",
            field=models.IntegerField(null=True),
        ),
    ]
