# Generated by Django 5.0 on 2023-12-30 14:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pos", "0004_temporarycustomercartitem_cashier_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("Cancelled", "Cancelled"),
                    ("Processed", "Processed"),
                    ("Pending", "Pending"),
                    ("Paid", "Paid"),
                ],
                max_length=255,
            ),
        ),
    ]
