# Generated by Django 5.0 on 2024-01-13 11:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0010_alter_inventory_created_alter_inventory_modified_and_more"),
        ("pos", "0010_creditorder"),
    ]

    operations = [
        migrations.AlterField(
            model_name="temporarycustomercartitem",
            name="item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="inventory.inventory"
            ),
        ),
    ]
