# Generated by Django 5.0.6 on 2024-08-09 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("deliveries", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="pickupstation",
            name="phone_number",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="delivery",
            name="delivery_type",
            field=models.CharField(
                choices=[
                    ("Self Pickup", "Self Pickup"),
                    ("Door Delivery", "Door Delivery"),
                    ("Pickup Station", "Pickup Station"),
                ],
                default="Self Pickup",
                max_length=255,
            ),
        ),
    ]
