# Generated by Django 5.0.6 on 2024-08-09 16:13

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("deliveries", "0002_pickupstation_phone_number_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="delivery",
            name="delivery_status",
            field=models.CharField(
                choices=[
                    ("Delivered", "Delivered"),
                    ("Transit", "Transit"),
                    ("Pending Dispatch", "Pending Dispatch"),
                    ("Initiated", "Initiated"),
                    ("Dispatched", "Dispatched"),
                ],
                default="Pending Dispatch",
                max_length=255,
            ),
        ),
        migrations.CreateModel(
            name="DeliveryStatusUpdate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(default=django.utils.timezone.now)),
                ("modified", models.DateTimeField(default=django.utils.timezone.now)),
                ("previous_status", models.CharField(max_length=255)),
                ("next_status", models.CharField(max_length=255)),
                (
                    "delivery",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="deliveries.delivery",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
