# Generated by Django 5.0.6 on 2024-08-09 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("deliveries", "0003_alter_delivery_delivery_status_deliverystatusupdate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="delivery",
            name="delivery_status",
            field=models.CharField(
                choices=[
                    ("Delivered", "Delivered"),
                    ("Transit", "Transit"),
                    ("Pending Dispatch", "Pending Dispatch"),
                    ("Initiated", "Initiated"),
                    ("Dispatched", "Dispatched"),
                    ("Abandoned", "Abandoned"),
                ],
                default="Pending Dispatch",
                max_length=255,
            ),
        ),
    ]
