# Generated by Django 5.0.6 on 2024-08-09 19:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("deliveries", "0005_deliverydriver_delivery_driver"),
        ("users", "0014_alter_user_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="deliveryaddress",
            name="customer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="users.customer"
            ),
        ),
    ]
