# Generated by Django 5.0.6 on 2024-08-09 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("deliveries", "0006_alter_deliveryaddress_customer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="deliveryaddress",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
