# Generated by Django 5.0.6 on 2024-08-09 20:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("deliveries", "0007_alter_deliveryaddress_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="deliveryaddress",
            name="pickup_station",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="deliveries.pickupstation",
            ),
        ),
    ]
