# Generated by Django 5.0.6 on 2024-08-10 10:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("deliveries", "0008_alter_deliveryaddress_pickup_station"),
        ("users", "0014_alter_user_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="delivery",
            name="customer",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="users.customer",
            ),
        ),
    ]
