# Generated by Django 5.0.6 on 2024-08-10 11:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("deliveries", "0010_county_town"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pickupstation",
            name="county",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="deliveries.county",
            ),
        ),
        migrations.AlterField(
            model_name="pickupstation",
            name="town",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="deliveries.town",
            ),
        ),
    ]
