# Generated by Django 5.0.6 on 2024-08-11 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("deliveries", "0011_alter_pickupstation_county_alter_pickupstation_town"),
    ]

    operations = [
        migrations.AddField(
            model_name="deliveryaddress",
            name="id_number",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="deliveryaddress",
            name="name",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="deliveryaddress",
            name="phone_number",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
