# Generated by Django 5.0.6 on 2024-08-12 14:10

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("deliveries", "0012_deliveryaddress_id_number_deliveryaddress_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="deliveryaddress",
            name="county",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="deliveries.county",
            ),
        ),
        migrations.AddField(
            model_name="deliveryaddress",
            name="town",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="deliveries.town",
            ),
        ),
        migrations.CreateModel(
            name="SubCounty",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(default=django.utils.timezone.now)),
                ("modified", models.DateTimeField(default=django.utils.timezone.now)),
                ("name", models.CharField(max_length=255)),
                (
                    "county",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="deliveries.county",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="deliveryaddress",
            name="sub_county",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="deliveries.subcounty",
            ),
        ),
        migrations.AddField(
            model_name="pickupstation",
            name="sub_county",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="deliveries.subcounty",
            ),
        ),
        migrations.AddField(
            model_name="town",
            name="sub_county",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="deliveries.subcounty",
            ),
        ),
        migrations.CreateModel(
            name="Ward",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(default=django.utils.timezone.now)),
                ("modified", models.DateTimeField(default=django.utils.timezone.now)),
                ("name", models.CharField(max_length=255)),
                (
                    "sub_county",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="deliveries.subcounty",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="deliveryaddress",
            name="ward",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="deliveries.ward",
            ),
        ),
        migrations.AddField(
            model_name="pickupstation",
            name="ward",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="deliveries.ward",
            ),
        ),
        migrations.AddField(
            model_name="town",
            name="ward",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="deliveries.ward",
            ),
        ),
    ]
