# Generated by Django 5.0.6 on 2024-08-12 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("deliveries", "0013_deliveryaddress_county_deliveryaddress_town_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="deliveryaddress",
            name="town",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="pickupstation",
            name="town",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
