# Generated by Django 5.0.6 on 2024-08-12 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("deliveries", "0015_branch"),
    ]

    operations = [
        migrations.AddField(
            model_name="deliveryaddress",
            name="address_type",
            field=models.CharField(
                choices=[
                    ("Self Pickup", "Self Pickup"),
                    ("Door Delivery", "Door Delivery"),
                    ("Pickup Station", "Pickup Station"),
                ],
                default="Pickup Station",
                max_length=255,
            ),
        ),
    ]
