# Generated by Django 5.0.6 on 2024-08-12 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("deliveries", "0016_deliveryaddress_address_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="pickupstation",
            name="station_type",
            field=models.CharField(
                choices=[("General", "General"), ("Shop", "Shop")],
                default="General",
                max_length=255,
            ),
        ),
    ]
