# Generated by Django 5.0.6 on 2024-08-15 10:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("deliveries", "0017_pickupstation_station_type"),
        ("users", "0014_alter_user_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="deliveryaddress",
            name="customer",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="users.customer",
            ),
        ),
    ]
