# Generated by Django 5.0 on 2024-01-13 11:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reports", "0002_productsale_unit_price_alter_productsale_total_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productsale",
            name="created",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="productsale",
            name="modified",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
