# Generated by Django 5.0 on 2024-01-02 15:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pos", "0005_alter_order_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="created",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="modified",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="created",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="modified",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name="temporarycustomercartitem",
            name="created",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="temporarycustomercartitem",
            name="modified",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
