# Generated by Django 5.0 on 2024-01-06 09:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pos", "0008_order_order_receipt"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="order_type",
            field=models.CharField(
                choices=[("Paid", "Paid"), ("Credit", "Credit")],
                max_length=255,
                null=True,
            ),
        ),
    ]
