# Generated by Django 5.0 on 2024-01-15 09:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pos", "0014_orderitem_cashier_id_orderitem_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("Mpesa", "Mpesa"),
                    ("Cash", "Cash"),
                    ("Wallet", "Wallet"),
                    ("Credit", "Credit"),
                ],
                max_length=255,
                null=True,
            ),
        ),
    ]
