# Generated by Django 5.0.6 on 2024-05-16 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pos", "0015_alter_order_payment_method"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="order_source",
            field=models.CharField(
                choices=[("Store", "Store"), ("Online", "Online")],
                default="Store",
                max_length=255,
            ),
        ),
    ]
