# Generated by Django 5.0.6 on 2024-07-18 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pos", "0016_order_order_source"),
    ]

    operations = [
        migrations.AddField(
            model_name="temporarycustomercartitem",
            name="paid",
            field=models.BooleanField(default=False),
        ),
    ]
