# Generated by Django 5.0.6 on 2024-07-18 11:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pos", "0017_temporarycustomercartitem_paid"),
    ]

    operations = [
        migrations.AddField(
            model_name="temporarycustomercartitem",
            name="order",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, to="pos.order"
            ),
        ),
    ]
