# Generated by Django 5.0.6 on 2024-08-10 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pos", "0018_temporarycustomercartitem_order"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="order_type",
            field=models.CharField(
                choices=[("Paid", "Paid"), ("Credit", "Credit"), ("Online", "Online")],
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("Mpesa", "Mpesa"),
                    ("Cash", "Cash"),
                    ("Wallet", "Wallet"),
                    ("Credit", "Credit"),
                    ("Online", "Online"),
                ],
                max_length=255,
                null=True,
            ),
        ),
    ]
